### ISSUE TITLE
Improve information display

### ISSUE THREAD

**Issue by brunorochapaiva** [georgejkaye/thesis-tracker#12]
I think the current way that information is displayed is too succint. For readability and user friendliness, I think more text should be added, bringing the current landing page closer in line with the previous iterations.

**Comment by georgejkaye** [comment]
Could you provide a mockup of your vision in Pinta?

**Comment by brunorochapaiva** [comment]
What a weirdly prescient request. Why yes I could, I think something like this would look good:

![image](https://github.com/georgejkaye/thesis-tracker/assets/56236873/109daca3-0287-475d-ad9b-214ce218657a)

**Comment by georgejkaye** [comment]
Not a bad idea!

**Comment by georgejkaye** [comment]
It looks lovely on desktop but diabolical on mobile

**Comment by georgejkaye** [comment]
Better than before but on small screens it doesn't fit into one page... 

![signal-2023-11-01-07-54-34-656.jpg](https://github.com/georgejkaye/thesis-tracker/assets/7274805/eb6b4399-3fea-46e1-b9b5-efd14da33d3e)
