### ISSUE TITLE
OMG HE'S LATE, HE'S MISSED THE SUBMISSION DEADLINE

### ISSUE THREAD

**Issue by FrozenDude101** [georgejkaye/thesis-tracker#34]
![image](https://github.com/user-attachments/assets/ac9f425b-1d98-4641-b7a5-019a0b55a26c)

**Comment by georgejkaye** [comment]
Fear not, readers, I submitted my thesis on 28/06/2024, and successfully defended it on 11/09/2024.

**Comment by FrozenDude101** [comment]
yeah, well I successfully defended your mum last night
